name: Android CI

on:
  push:
    branches: [ main, "feature/**" ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.7
      - name: Install Android SDK components
        run: |
          sdkmanager --install "platform-tools" "platforms;android-35" "build-tools;35.0.0"
      - name: Write gradle.properties additions
        run: |
          echo "YOUTUBE_API_KEY=${{ secrets.YOUTUBE_API_KEY }}" >> gradle.properties
        working-directory: android-youtube-top
      - name: Unit tests (core)
        run: gradle :core:test --no-daemon
        working-directory: android-youtube-top
      - name: Build
        run: gradle :app:assembleDebug
        working-directory: android-youtube-top
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: android-youtube-top/app/build/outputs/apk/debug/app-debug.apk
          if-no-files-found: error
          retention-days: 7
